version: "3.9"

services:
  nextcloud:
    build:
      context: "./nextcloud/"
      args:
        NC_VERSION: ${NC_VERSION}
    environment:
      - TZ=Asia/Taipei
      - MYSQL_HOST=mariadb
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_DATABASE}
      - REDIS_HOST=redis
      - REDIS_HOST_PASSWORD=${RD_PASS}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NC_TRUST_DOMAINS}
      - NEXTCLOUD_UPDATE=1
      - PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT}
    depends_on:
      - mariadb
      - redis
    volumes:
      - nc-data:/var/www/html
    container_name: "nextcloud"
    restart: always
    deploy:
      resources:
        limits:
          memory: 4096M

  onlyoffice:
    image: onlyoffice/documentserver:${OFFICE_VERSION}
    environment:
      - TZ=Asia/Taipei
      - JWT_ENABLED=false
    volumes:
      - onlyoffice-data:/var/www/onlyoffice/Data
    container_name: "onlyoffice"
    restart: always

  # drawio:
  #   image: jgraph/drawio
  #   container_name: drawio
  #   restart: always
  #   ports:
  #     - "8081:8080"
  #     - "8443:8443"
  #   environment:
  #     PUBLIC_DNS: drawio
  #     ORGANISATION_UNIT: IT
  #     ORGANISATION: SK
  #     CITY: kaohsiung
  #     STATE: Taiwan
  #     COUNTRY_CODE: Taiwan
  #   healthcheck:
  #     test: ["CMD-SHELL", "curl -f http://drawio:8080 || exit 1"]
  #     interval: 1m30s
  #     timeout: 10s
  #     retries: 5
  #     start_period: 10s

  nginx:
    image: nginx:latest
    depends_on:
      - nextcloud
    ports:
      - ${NC_PORT}:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - nc-data:/var/www/html
    container_name: nginx-server
    restart: always

  mariadb:
    image: mariadb:${DB_VERSION}
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-read-only-compressed=OFF
    environment:
      - TZ=Asia/Taipei
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_DATABASE}
    ports:
      - "${DB_PORT}"
    volumes:
      - db-data:/var/lib/mysql
    container_name: "${DB_NAME}"
    restart: always

  redis:
    image: redis:${RD_VERSION}
    command: "redis-server --requirepass ${RD_PASS}"
    deploy:
      resources:
        limits:
          memory: 512M
    container_name: "${RD_NAME}"
    restart: always

volumes:
  db-data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${DB_DATAPATH}"
    external: false

  nc-data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${NC_DATAPATH}"
    external: false

  onlyoffice-data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${OFFICE_DATAPATH}"
    external: false
