version: "3.9"

services:
    nextcloud:
        build:
            context: "./nextcloud/"
            args:
                NC_VERSION: ${NC_VERSION}
        environment:
            - TZ=Asia/Taipei
            - MYSQL_HOST=mariadb
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASS}
            - MYSQL_DATABASE=${DB_DATABASE}
        depends_on:
            - mariadb
        links:
            - mariadb
        ports:
            - "${NC_PORT}:80"
        volumes:
            - nc-data:/var/www/html
        container_name: "${NC_NAME}"
        restart: always

    mariadb:
        image: mariadb:${DB_VERSION}
        restart: always
        command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
        environment:
            - TZ=Asia/Taipei
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASS}
            - MYSQL_DATABASE=${DB_DATABASE}
        volumes:
            - db-config:/var/lib/mysql
        container_name: "${DB_NAME}"
        restart: always

volumes:
    db-config:
        driver: local
        driver_opts:
            type: "none"
            o: "bind"
            device: "./config/mariadb/"
        external: false

    nc-data:
        driver: local
        driver_opts:
            type: "none"
            o: "bind"
            device: "${NC_DATAPATH}"
        external: false
