version: "3.9"

services:
  nextcloud:
    build:
      context: "./nextcloud/"
      args:
        NC_VERSION: ${NC_VERSION}
    environment:
      - TZ=Asia/Taipei
      - MYSQL_HOST=mariadb
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_DATABASE}
      - REDIS_HOST=redis
      - REDIS_HOST_PASSWORD=${RD_PASS}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NC_TRUST_DOMAINS}
      - NEXTCLOUD_UPDATE=1
      - PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT}
    depends_on:
      - mariadb
      - redis
    volumes:
      - nc-data:/var/www/html
    container_name: "nextcloud"
    restart: always
    deploy:
      resources:
        limits:
          memory: 8192M

  onlyoffice:
    # image: onlyoffice/documentserver:${OFFICE_VERSION}
    # docker pull thomisus/onlyoffice-documentserver-unlimited:7.3.3
    image: thomisus/onlyoffice-documentserver-unlimited:7.5.1
    environment:
      - TZ=Asia/Taipei
      - JWT_ENABLED=true
      - JWT_SECRET=${OFFICE_PASS}
      # After 7.3.3 version
      - ALLOW_PRIVATE_IP_ADDRESS=true
    volumes:
      - onlyoffice-data:/var/www/onlyoffice/Data
    container_name: "onlyoffice"
    restart: always
    deploy:
      resources:
        limits:
          memory: 1536M

  drawio:
    image: jgraph/drawio:${DWIO_VERSION}
    container_name: drawio
    restart: always
    environment:
      DRAWIO_BASE_URL: https://${HOST_DOMAIN}/drawio/
      DRAWIO_LIGHTBOX_URL: https://${HOST_DOMAIN}/
      # 沒有設定就是用官方的export server
      # EXPORT_URL: https://${HOST_DOMAIN}/drawio-export/
      PUBLIC_DNS: drawio
      ORGANISATION_UNIT: IT
      ORGANISATION: SK
      CITY: kaohsiung
      STATE: Taiwan
      COUNTRY_CODE: Taiwan
    depends_on:
      - nginx
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://drawio:8080 || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 10s

  # image-export:
  #   image: jgraph/export-server:latest
  #   container_name: drawio-export
  #   expose:
  #     - "8000"
  #   environment:
  #     DRAWIO_BASE_URL: ${HOST_DOMAIN}
  #     DRAWIO_SERVER_URL: https://${HOST_DOMAIN}/drawio/
  #   volumes:
  #     - ./drawio/fonts:/usr/share/fonts/drawio
  #   restart: always

  nginx:
    image: nginx:latest
    depends_on:
      - nextcloud
      - onlyoffice
    ports:
      - ${NC_PORT}:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - nc-data:/var/www/html
    container_name: nginx-server
    restart: always
    deploy:
      resources:
        limits:
          memory: 256M

  mariadb:
    image: mariadb:${DB_VERSION}
    command: --transaction-isolation=READ-COMMITTED --log-bin --binlog-format=ROW --innodb-read-only-compressed=OFF
    environment:
      - TZ=Asia/Taipei
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_DATABASE}
    ports:
      - "${DB_PORT}"
    volumes:
      - db-data:/var/lib/mysql
    container_name: "${DB_NAME}"
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M

  redis:
    image: redis:${RD_VERSION}
    command: "redis-server --requirepass ${RD_PASS}"
    container_name: "${RD_NAME}"
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M

volumes:
  db-data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${DB_DATAPATH}"
    external: false

  nc-data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${NC_DATAPATH}"
    external: false

  onlyoffice-data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${OFFICE_DATAPATH}"
    external: false
