version: "3.9"

services:
    nextcloud:
        build:
            context: "./nextcloud/"
            args:
                NC_VERSION: ${NC_VERSION}
        environment:
            - TZ=Asia/Taipei
            - MYSQL_HOST=mariadb
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASS}
            - MYSQL_DATABASE=${DB_DATABASE}
            - REDIS_HOST=redis
            - REDIS_HOST_PASSWORD=${RD_PASS}
        depends_on:
            - mariadb
            - redis
        links:
            - mariadb
        ports:
            - "${NC_PORT}:80"
        volumes:
            - nc-data:/var/www/html
        container_name: "${NC_NAME}"
        restart: always

    mariadb:
        image: mariadb:${DB_VERSION}
        command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
        environment:
            - TZ=Asia/Taipei
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASS}
            - MYSQL_DATABASE=${DB_DATABASE}
        ports:
            - "${DB_PORT}"
        volumes:
            - db-data:/var/lib/mysql
        container_name: "${DB_NAME}"
        restart: always

    redis:
        image: redis:${RD_VERSION}
        container_name: "${RD_NAME}"
        command: "redis-server --requirepass ${RD_PASS}"
        deploy:
            resources:
                limits:
                    memory: 200M
        restart: always

volumes:
    db-data:
        driver: local
        driver_opts:
            type: "none"
            o: "bind"
            device: "${DB_DATAPATH}"
        external: false

    nc-data:
        driver: local
        driver_opts:
            type: "none"
            o: "bind"
            device: "${NC_DATAPATH}"
        external: false
