ARG NC_VERSION
FROM nextcloud:${NC_VERSION}

ARG GID
RUN groupadd -g ${GID} vboxsf
RUN usermod -aG vboxsf root
RUN usermod -aG root www-data

RUN apt-get update && apt-get install -y --no-install-recommends $(apt-cache search libmagickcore-6.q[0-9][0-9]-[0-9]-extra | cut -d " " -f1)
